### ISSUE TITLE
Input Device config does not change microphone input

### ISSUE THREAD

**Issue by padlocks** [MrAyianaLex/streamdeck-steelseries-sonar#1]
I am unable to get the Input Device config button to work regardless of what settings I use. I have tried both streamer and classic mode, as well as different microphone inputs. Usage of the broken button results in the plugin restarting.

> 16:33:56.772                     StreamDeck                        ESDCustomPlugin::onNativeProcessFinished():     The plugin 'SteelSeries Sonar Integration' exited normally with code -532462766
16:33:56.772                     StreamDeck                        ESDCustomPlugin::restartNativeProcess():        Restarting plugin 'SteelSeries Sonar Integration' in 0 seconds(s)

Side note: Output Device config works perfectly. Great work on the plugin, I use it all the time.

**Comment by MrAyianaLex** [comment]
Hello,
The button works perfectly with me.
It happens that following a Windows update or other software, than the identifiers of the foreign exchange devices.
This can be seen because the icon remains white.
If that doesn't solve the problem, I need the file "%appdata%\Elgato\StreamDeck\Plugins\com.mrayianalex.sonar.sdPlugin\pluginlog.log" to have a track

**Comment by padlocks** [comment]
Currently using:
Steelseries 50.1.0
Windows 22H2 22621.2428
StreamDeck firmware: 1.01.000
StreamDeck software: 6.4.1.19697
Latest version of this plugin.

```2023-11-21 03:04:35.9736|DEBUG|com.mrayianalex.sonar|1|Logger Initialized
2023-11-21 03:04:36.0062|INFO|com.mrayianalex.sonar|1|Plugin [com.mrayianalex.sonar] Loading - 11 Actions Found
2023-11-21 03:04:36.7437|DEBUG|com.mrayianalex.sonar|1|Plugin Loaded: UUID: 5EA819F05BA8BA26DB5714CABFAB839A Device Info: Devices:
[Id: 4D2119D7FA003FDACDC6ED3789C0D5AD Type: StreamDeckClassic Size: Rows: 3 Columns: 5]
ApplicationInfo: Language: en Platform: windows Version: 6.4.1.19697
PluginInfo: Version: 1.0
2023-11-21 03:04:36.7437|INFO|com.mrayianalex.sonar|1|Plugin version: 1.0
2023-11-21 03:04:36.7437|INFO|com.mrayianalex.sonar|1|Connecting to Stream Deck...
2023-11-21 03:04:38.8675|INFO|com.mrayianalex.sonar|1|Connected to Stream Deck
2023-11-21 03:04:38.8675|INFO|com.mrayianalex.sonar|1|GlobalSettingsManager initialized
2023-11-21 03:04:38.9031|INFO|com.mrayianalex.sonar|4|Ignoring SetGlobalSettings as they were not yet loaded
2023-11-21 03:04:39.1980|INFO|com.mrayianalex.sonar|4|sonarWebServerAddress : http://localhost:50656/
2023-11-21 03:04:39.2278|INFO|com.mrayianalex.sonar|4|SteelSeriesSonar.SonarSwitchInputDeviceAction FetchPlaybackDevices returned 6 captures devices
2023-11-21 03:04:39.2718|INFO|com.mrayianalex.sonar|4|Ignoring SetGlobalSettings as they were not yet loaded
2023-11-21 03:05:36.7038|INFO|com.mrayianalex.sonar|9|SteelSeriesSonar.SonarSwitchInputDeviceAction KeyPressed
2023-11-21 03:05:36.7350|FATAL|com.mrayianalex.sonar|12|Unhandled Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at SteelSeriesSonar.SSSManager.PutData(String target) in \\NAS-de-Al\projet\DevCSharp\streamdeck-SteelSeriesSonar\SteelSeriesSonar\SSSManager.cs:line 99
   at SteelSeriesSonar.SonarSwitchInputDeviceAction.KeyPressed(KeyPayload payload) in \\NAS-de-Al\projet\DevCSharp\streamdeck-SteelSeriesSonar\SteelSeriesSonar\Actions\SonarSwitchInputDevice.cs:line 137
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2023-11-21 03:05:39.5185|DEBUG|com.mrayianalex.sonar|1|Logger Initialized
2023-11-21 03:05:39.5329|INFO|com.mrayianalex.sonar|1|Plugin [com.mrayianalex.sonar] Loading - 11 Actions Found
2023-11-21 03:05:39.7345|DEBUG|com.mrayianalex.sonar|1|Plugin Loaded: UUID: 3F09C5CFEAFD91FDA0602CD0E6D8360D Device Info: Devices:
[Id: 4D2119D7FA003FDACDC6ED3789C0D5AD Type: StreamDeckClassic Size: Rows: 3 Columns: 5]
ApplicationInfo: Language: en Platform: windows Version: 6.4.1.19697
PluginInfo: Version: 1.0

**Comment by MrAyianaLex** [comment]
Can you confirm that in stream mode, it works, and in classic mode, it doesn't work ?
If so, I found the cause

**Comment by padlocks** [comment]
I can't get it to work in either classic mode or stream mode.

**Comment by MrAyianaLex** [comment]
Please, test 1.3 realease

**Comment by padlocks** [comment]
1.3 fixes the problem in classic mode, thank you so much! Streamer mode is still broken though.
```
2023-11-21 13:18:48.3089|INFO|com.mrayianalex.sonar|9|SteelSeriesSonar.SonarSwitchInputDeviceAction KeyPressed
2023-11-21 13:18:49.9241|INFO|com.mrayianalex.sonar|9|PutData(streamRedirections/mic/deviceId/{0.0.1.00000000}.{38cf330d-5e01-4d1b-b9bd-f1912f70a1a9}) : {"engineDeviceId":null,"engineDeviceName":null,"streamRedirectionId":"mic","deviceId":"{0.0.1.00000000}.{38cf330d-5e01-4d1b-b9bd-f1912f70a1a9}","status":[],"isRunning":true}
2023-11-21 13:18:52.7356|INFO|com.mrayianalex.sonar|9|SteelSeriesSonar.SonarSwitchInputDeviceAction KeyPressed
2023-11-21 13:18:53.8139|INFO|com.mrayianalex.sonar|9|PutData(streamRedirections/mic/deviceId/{0.0.1.00000000}.{fa76d192-30cb-45e3-b525-94bbf6b50db9}) : {"engineDeviceId":null,"engineDeviceName":null,"streamRedirectionId":"mic","deviceId":"{0.0.1.00000000}.{fa76d192-30cb-45e3-b525-94bbf6b50db9}","status":[],"isRunning":true}

**Comment by MrAyianaLex** [comment]
Sorry, I don't understand why it works at home and why it doesn't work at home.
From what I see in your log, the call is made properly, and does not return any error.
